# fly.toml app configuration file generated for rss-to-tana on 2023-07-21T12:04:26+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rss-to-tana-2"
primary_region = "cdg"

[build]
dockerfile = "rss-to-tana/Dockerfile"

[deploy]
strategy = "immediate"

[env]
NODE_ENV = "production"
SYNC_FEEDS = true

[[services]]
  auto_stop_machines = "off"
  auto_start_machines = false

  [[services.ports]]
    handlers = ["http"]
    port = 80

[checks]
  [checks.health]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"
    type = "http"

swap_size_mb = 512