app = "rss-to-tana"
primary_region = "cdg"

[build]
dockerfile = "rss-to-tana/Dockerfile"

[deploy]
strategy = "immediate"

[env]
NODE_ENV = "production"
SYNC_FEEDS = true

[http_service]
  internal_port = 8080
  auto_stop_machines = "off"
  auto_start_machines = false

swap_size_mb = 512