app = "rss-to-tana"
primary_region = "cdg"

[build]
  dockerfile = "rss-to-tana/Dockerfile"

[deploy]
  strategy = "immediate"

[env]
  NODE_ENV = "production"
  SYNC_FEEDS = true
  NODE_OPTIONS = "--max-old-space-size=356"


[http_service]
  internal_port = 8080
  auto_stop_machines = "off"
  auto_start_machines = false

swap_size_mb = 512

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
