name: Deploy rss-to-tana
on:
  push:
    branches:
      - main
    paths:
      - rss-to-tana/**

defaults:
  run:
    working-directory: rss-to-tana

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@v1.5
        with:
          version: 0.1.63 # as of 21/07/2023
      - run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
